#Use node 20
FROM node:20-alpine

#set working dir
WORKDIR/app

#install dependencies
COPY package*.json ./
RUN npm ci --only=production

#copy app source
COPY . .

# Expose backend port
EXPOSE 3000

# Start server
CMD ["npm", "server.js"]
